/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.view;

import neu.edu.csye6200.model.Student;
import neu.edu.csye6200.model.Record;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import neu.edu.csye6200.Interface.*;
import neu.edu.csye6200.controller.*;

/**
 *
 * @author faun
 */
public class ViewRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRecordJPanel
     */
    private JPanel cardL;
    private Student student;

    public ViewRecordJPanel(JPanel cardL, Student student) {
        initComponents();
        this.cardL = cardL;
        this.student = student;
    }
    String[] head = new String[]{
        "ID", "Name", "Age", "HepB", "HepBDate", "RV", "RVDate",
        "DTap", "DTapDate", "Hib", "HibDate", "PCV13", "PCV13Date", "IPV",
        "IPVDate", "IIV", "IIVDate"
    };
    RecordAPI RI = new RecordImpl();
    public Object[][] queryData() {

     
        List<Record> list = RI.ShowRecord();
        Object[][] data = new Object[list.size()][17];

        for (int i = 0; i < list.size(); i++) {
            for (int j = 0; j < 17; j++) {
                data[i][0] = list.get(i).getId();
                data[i][1] = list.get(i).getName();
                data[i][2] = list.get(i).getage();
                data[i][3] = list.get(i).getHepB();
                data[i][4] = list.get(i).getHepBDate();
                data[i][5] = list.get(i).getRV();
                data[i][6] = list.get(i).getRVDate();
                data[i][7] = list.get(i).getDTaP();
                data[i][8] = list.get(i).getDTaPDate();
                data[i][9] = list.get(i).getHib();
                data[i][10] = list.get(i).getHibDate();
                data[i][11] = list.get(i).getPCV13();
                data[i][12] = list.get(i).getPCV13Date();
                data[i][13] = list.get(i).getIPV();
                data[i][14] = list.get(i).getIPVDate();
                data[i][15] = list.get(i).getIIV();
                data[i][16] = list.get(i).getIIVDate();

            }
        }
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("View Student Record");

        jButton3.setBackground(new java.awt.Color(181, 219, 240));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(181, 219, 240));
        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(queryData(),head));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(181, 219, 240));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1)
                        .addContainerGap(512, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cardL.remove(this);
        CardLayout layout = (CardLayout) cardL.getLayout();
        layout.previous(cardL);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if (this.jTable1.getSelectedRow() < 0) {
			//删除操作错误.setVisible(true);
			return;
		}
		
		int record = Integer.valueOf(this.jTable1.getValueAt(
				this.jTable1.getSelectedRow(), 0).toString());

		System.out.println(record + "delet");
		RI.delete(record);
                RI.ShowRecord();
                   jTable1.setModel(new javax.swing.table.DefaultTableModel(queryData(),head));
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            csvUtil cu = new csvUtil();
        try {
            cu.exportCsv(head, queryData(), jLabel1.getText());
        } catch (IOException ex) {
            Logger.getLogger(UpcomingJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(UpcomingJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(UpcomingJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public Object[][] searchResult(int ID) {
        List<Record> list = RI.search(ID);

        Object[][] data = new Object[list.size()][17];

        for (int i = 0; i < list.size(); i++) {
            for (int j = 0; j < 17; j++) {
                data[i][0] = list.get(i).getId();
                data[i][1] = list.get(i).getName();
                data[i][2] = list.get(i).getage();
                data[i][3] = list.get(i).getHepB();
                data[i][4] = list.get(i).getHepBDate();
                data[i][5] = list.get(i).getRV();
                data[i][6] = list.get(i).getRVDate();
                data[i][7] = list.get(i).getDTaP();
                data[i][8] = list.get(i).getDTaPDate();
                data[i][9] = list.get(i).getHib();
                data[i][10] = list.get(i).getHibDate();
                data[i][11] = list.get(i).getPCV13();
                data[i][12] = list.get(i).getPCV13Date();
                data[i][13] = list.get(i).getIPV();
                data[i][14] = list.get(i).getIPVDate();
                data[i][15] = list.get(i).getIIV();
                data[i][16] = list.get(i).getIIVDate();

            }
        }
        return data;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
