/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.view;

import neu.edu.csye6200.model.Student;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import neu.edu.csye6200.Interface.StudentAPI;
import neu.edu.csye6200.Interface.StudentDataAPI;
import neu.edu.csye6200.controller.StudentDataImpl;
import neu.edu.csye6200.controller.StudentImpl;


/**
 *
 * @author faun
 */
public class ViewStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudentJPanel
     */
    private JPanel cardL;
    private Student student;
    private StudentDataAPI StuI = new StudentDataImpl();
    public ViewStudentJPanel(JPanel cardL, Student student) {
        initComponents();
        this.cardL = cardL;
        this.student = student;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String[] head = new String [] {
                "ID", "Name", "Grade", "Age", "Address", "RegDate", "RenewDate", "FatherName", "MotherName", "Phone"
            };
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setBackground(new java.awt.Color(181, 219, 240));
        jButton6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButton6.setText("<<Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("View Student Data");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(queryData(),head));
        jScrollPane1.setViewportView(jTable1);

        jButtonDel.setBackground(new java.awt.Color(181, 219, 240));
        jButtonDel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonDel.setText("Delete");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(209, 209, 209)
                            .addComponent(jLabel1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        cardL.remove(this);
        CardLayout layout = (CardLayout)cardL.getLayout();
        layout.previous(cardL);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        StudentAPI SA = new StudentImpl();
          if (this.jTable1.getSelectedRow() < 0) {
			//删除操作错误.setVisible(true);
			return;
		}
		int record = Integer.valueOf(this.jTable1.getValueAt(
				this.jTable1.getSelectedRow(), 0).toString());

		System.out.println(record + "delet");
		SA.delete(record);
                StuI.showStuentData();
                   jTable1.setModel(new javax.swing.table.DefaultTableModel(queryData(),head));
    }//GEN-LAST:event_jButtonDelActionPerformed

    public Object[][] queryData() {
        List<Student> list = StuI.showStuentData();
        Object[][] data = new Object[list.size()][10];

        for (int i = 0; i < list.size(); i++) {
            for (int j = 0; j < 17; j++) {
                data[i][0] = list.get(i).getId();
                data[i][1] = list.get(i).getName();
                data[i][2] = list.get(i).getGrade();
                data[i][3] = list.get(i).getAge();
                data[i][4] = list.get(i).getAddress();
                data[i][5] = list.get(i).getRegistryDate();
                data[i][6] = list.get(i).getRenewDate();
                data[i][7] = list.get(i).getFatherName();
                data[i][8] = list.get(i).getMotherName();
                data[i][9] = list.get(i).getPhoneNumber();
            }
        }
        return data;
    }
    
    public Object[][] searchResult(int ID) {
        List<Student> list = StuI.search(ID);
        Object[][] data = new Object[list.size()][10];

        for (int i = 0; i < list.size(); i++) {
            for (int j = 0; j < 17; j++) {
                data[i][0] = list.get(i).getId();
                data[i][1] = list.get(i).getName();
                data[i][2] = list.get(i).getGrade();
                data[i][3] = list.get(i).getAge();
                data[i][4] = list.get(i).getAddress();
                data[i][5] = list.get(i).getRegistryDate();
                data[i][6] = list.get(i).getRenewDate();
                data[i][7] = list.get(i).getFatherName();
                data[i][8] = list.get(i).getMotherName();
                data[i][9] = list.get(i).getPhoneNumber();
            }
        }
        return data;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
